### ISSUE TITLE
Viewer for images with .tgd format

### ISSUE THREAD

**Issue by arrfou99** [marlam/wurblpt-mirror#1]
hello, 
I have run the wurblpt-tof-example  and I would like to visualize the resulted images which are now in a .tgd format. 

I have tried the TGD library to convert with the following code but I got an error 
` ./tgd convert -o FORMAT=stb frame0002-phase1-images.tgd frame0002-phase1-images.png`

and the error I got is:
`tgd convert: frame0002-phase1-images.png: unsupported file features
`
Ideally I would like to see all images at runtime but for now if I can view the results in png or jpeg format that would be enough.

Thanks

**Comment by marlam** [comment]
The problem here is that the data is floating point, and you cannot store that in .png, that's why tgd complains.
You have the following options:

- Use a file format that can store floating point and is always supported, e.g. csv or exr, and use a viewer for these formats,
- Or build tgd with libraries for hdf5 or tiff or pfs, and use one of these file formats and a corresponding viewer,
- Or use [qv](https://marlam.de/qv) as a viewer. Qv is based on tgd and therefore understands all its formats.

You don't need `tgd convert` to save the data in another format; you can simply replace `.tgd` with `.h5` (for example) in `wurblpt-tof-example.cpp`.

**Comment by arrfou99** [comment]
Great. I have tried replacing .tgd with .h5 and it works. 
I have tried also qv viewer and it is a  pretty nice tool to use. Well done.
