### ISSUE TITLE
Intensity image calculation

### ISSUE THREAD

**Issue by arrfou99** [marlam/wurblpt-mirror#2]
Hello,
I have tried the wurblpt-tof-hci example to load the hci 3D model. Everything looks fine except the intensity image which seems to be wrong . This is not he case when running the wurblpt-tof-example. I am new to this field but it seems that the intensity formula is not giving the correct intensity image result. Here the phase shift is the taps A-B from the phase images.

`
 float intensity = 0.5f * (D[0] + D[1] + D[2] + D[3]);
`
![image](https://github.com/marlam/wurblpt-mirror/assets/16118450/46f5f9aa-f739-442b-8533-5e155a1fbb4f)
![image](https://github.com/marlam/wurblpt-mirror/assets/16118450/1e33bd3b-7fe5-46e4-ac4b-04c474700ccc)

![image](https://github.com/marlam/wurblpt-mirror/assets/16118450/cf14631f-cee8-4ba6-9e7d-5d4273f857de)

**Comment by marlam** [comment]
The intensity image shows the limitation of our sensor model.

In an ideal environment and in the absence of systematic errors, the sum of the four phase images is zero, and therefore the intensity as computed by `intensity = 0.5f * (D[0] + D[1] + D[2] + D[3]);` must be zero.

So the only way to get values different from zero is by simulating systematic errors.

By default, `wurblpt-tof-hcibox` simulates just a little bit of shot noise. This gives the values you see. If you increase `shotNoiseFactor` e.g. to 10, then the intensity values scale accordingly. If you reduce the factor to zero, you only get the remnants of the Monte Carlo path tracing simulation, i.e. values that will converge to zero with an increasing number of samples per pixel.

In the `wurblt-tof-example` scene, another important source of systematic errors is simulated: motion. Because the phase images are taken at different intervals in time, they represent different scene states, and therefore their sum is not zero anymore. You will get higher intensity values, especially at the borders between foreground and background objects.

The formula for the intensity is taken from publicly available documentation of one brand of ToF sensors. The real sensors deliver intensity images that look a lot different. So either they compute intensity in a different way, or our sensor model fails to accurately simulate all relevant kinds of systematic errors; most probably it's a mixture of both.

[This thesis from Uni Graz](https://diglib.tugraz.at/download.php?id=608a88cfac002&location=browse) describes a much more advanced model of noise and chip imperfections in Sec. 3.2 and 3.3. It should be possible to implement this model as part of `SensorTofAMCW`. I just never found the time to do it.

**Comment by arrfou99** [comment]
Thank you for the reply and for sharing the s thesis from Uni Graz. Now it is a bit clear to me! If I got it right then the intensity image should be zero in ideal sensor with no environment light contributions. I see in real ToF sensors that the intensity is calculated as the average of four phases images is `intensity = 0.25f * (D[0] + D[1] + D[2] + D[3]);`  and the output image contains usually the light components from the environment which is not simulated here. In addition to this we have the systematic errors.

**Comment by marlam** [comment]
Right, environment light is another important factor, I forgot about that.

The code should work as-is with non-ToF light sources, i.e. `LightDiffuse` or `LightSpot`, if you want to try that.

WurblPT uses 4-component vectors for light transport and material reflectance, where the first three are RGB and the fourth is used for the unspecified infrared wavelength at which the simulated ToF sensor operates (`vec4(r, g, b, ir)`).
